framework:
    cache:
        #prefix_seed: your_vendor_name/app_name

        #app: cache.adapter.redis
        #default_redis_provider: redis://localhost

        #app: cache.adapter.apcu

        #pools:
            #my.dedicated.cache: null
